✨ Add http gateway
flashenv/flashenv pull request #11
Opened 2023-02-14 02:08 UTC by e-n-0

2023-02-14 08:47 UTC, francoisdtm requested changes
Nice job!

2023-02-14 08:47 UTC, francoisdtm commented on components/http-gateway/main.go
> +	log.Warnln(http.ListenAndServe(":8080", nil))
You can find an example [here](https://github.com/flashenv/flashenv/blob/main/components/dc-supervisor/cmd/run.go#L58-L59).

2023-02-14 08:47 UTC, francoisdtm commented on components/http-gateway/middlewares/subdomains.go
> +func parseSubdomains(r *http.Request, previewDomain string) []string {
Please use regex 👀

2023-02-14 08:47 UTC, francoisdtm commented on components/http-gateway/middlewares/subdomains.go
> +		port, err := strconv.Atoi(subdomains[0]) // Port int check
Please check that `0 < port <= 65535`.

2023-02-14 08:47 UTC, francoisdtm commented on components/http-gateway/middlewares/subdomains.go
> +func parseSubdomains(r *http.Request, previewDomain string) []string {
Something like `^([0-9]{1,5})\.([a-zA-Z0-9-_]+)\.` should be enough. It marches the port in group 1 and the workspace ID in group 2, ignoring the rest of the URL.

2023-02-14 08:47 UTC, francoisdtm commented on components/http-gateway/middlewares/workspaces.go
> +	// Check if the workspace is public or not
```suggestion
	// Check if the port is exposed to public or not
```

2023-02-15 01:53 UTC, e-n-0 commented on components/http-gateway/middlewares/subdomains.go
> +func parseSubdomains(r *http.Request, previewDomain string) []string {
The regex `^([0-9]{1,5})?\.?([a-zA-Z0-9-_]+)\.` will may be better because it also matches when no port is specified.

However how to deal with invalid domains like this one:
`11.red.80.blue.preview.flashenv.local`
The regex will takes the port `11` and name `red` and will discard other subdomains, but do we consider this domain valid or not?

2023-02-15 01:58 UTC, e-n-0 commented on components/http-gateway/middlewares/workspaces.go
> +	// Check if the workspace is public or not
No, I was referring to an upcoming feature on public workspace sharing.

2023-02-15 07:58 UTC, francoisdtm commented on components/http-gateway/middlewares/subdomains.go
> +func parseSubdomains(r *http.Request, previewDomain string) []string {
If the URL is invalid, then the gateway should drop the connection.

Let me benchmark some possible solutions, I'll post the results here.

2023-02-15 08:37 UTC, francoisdtm approved these changes

2023-02-15 08:37 UTC, francoisdtm commented on components/http-gateway/cmd/run.go
> +// Run the RPC server
```suggestion
// Run the http gateway
```

2023-02-15 08:37 UTC, francoisdtm commented on components/http-gateway/middlewares/subdomains.go
> +func parseSubdomains(r *http.Request, previewDomain string) []string {
The following code:

```go
package main_test

import (
	"regexp"
	"strings"
	"testing"
)

var previewDomain = "preview.flashenv.dev"
var host = "6829.red-carpet-5b5f.preview.flashenv.dev"

func BenchmarkTrim(b *testing.B) {
	for i := 0; i < b.N; i++ {
		host1 := strings.Split(host, ":")[0]
		host2 := strings.TrimSuffix(host1, "."+previewDomain)
		subdomains := strings.Split(host2, ".")
		_ = subdomains
	}
}

func BenchmarkRegex(b *testing.B) {
	for i := 0; i < b.N; i++ {
		regex := regexp.MustCompile(`^([0-9]{1,5})\.([a-zA-Z0-9-_]+)\.`)
		_ = regex.FindStringSubmatch(host)
	}
}

func BenchmarkRegexSlim(b *testing.B) {
	regex := regexp.MustCompile(`^([0-9]{1,5})\.([a-zA-Z0-9-_]+)\.`)
	for i := 0; i < b.N; i++ {
		_ = regex.FindStringSubmatch(host)
	}
}
```

Give the following results:

```bash
$ go test -bench=. -benchmem -benchtime=5s
goos: linux
goarch: amd64
pkg: github.com/flashenv/flashenv/http-gateway
cpu: Intel(R) Xeon(R) CPU E3-1275 V2 @ 3.50GHz
BenchmarkTrim-8         21620535               356.4 ns/op            48 B/op          2 allocs/op
BenchmarkRegex-8          382372             14251 ns/op            5825 B/op         49 allocs/op
BenchmarkRegexSlim-8     4311290              1223 ns/op             112 B/op          2 allocs/op
PASS
ok      github.com/flashenv/flashenv/http-gateway      20.286s
```

We should use operations on strings, as it is 3 times faster than using a precompiled regex.

2023-02-15 08:39 UTC, francoisdtm approved these changes

2023-02-15 08:39 UTC, merged